services:
  - type: web
    name: landing-web
    env: python
    buildCommand: "./landing/run.sh"
    startCommand: "python -m gunicorn landing.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: POSTGRES_PORT
        value: "5656"
      - key: POSTGRES_DB
        value: "landing"
      - key: POSTGRES_USER
        value: "root"
      - key: POSTGRES_PASSWORD
        value: "adminroot"
      - key: POSTGRES_HOST
        value: "landing_db"
    healthCheckPath: "/"
    autoDeploy: true

databases:
  - name: landing-db
    databaseName: landing
    user: root
