services:
  - type: web
    name: landing-web
    env: python
    buildCommand: "./landing/run.sh"
    startCommand: "gunicorn landing.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: POSTGRES_PORT
        value: "5656"
      - key: POSTGRES_DB
        value: "landing"
      - key: POSTGRES_USER
        value: "root"
      - key: POSTGRES_PASSWORD
        value: "adminroot"
      - key: POSTGRES_HOST
        value: "landing_db"
    healthCheckPath: "/"
    autoDeploy: true

databases:
  - name: ver_opina
    databaseName: ver_opina
    user: root
