# Generated by Django 4.2 on 2024-09-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatepage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
