# Generated by Django 4.2 on 2024-09-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="candidate_nick",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="election_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="municipio_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="site_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="uf",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
