# Generated by Django 4.2 on 2024-09-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate",
            "0002_candidate_candidate_nick_candidate_election_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="party_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
