# Generated by Django 4.2 on 2024-09-23 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_candidatepage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=255)),
                ("party_logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("party_description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="candidatepage",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="candidate.party"
            ),
        ),
    ]
