# Generated by Django 4.2 on 2024-09-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0003_alter_party_party_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="image",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="candidate_name",
            field=models.CharField(max_length=255, verbose_name="Nome do Candidato"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="candidate_nick",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome de Urna"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="election_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Número da Eleição"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidate.party",
                verbose_name="Partido",
            ),
        ),
    ]
