# Generated by Django 4.2 on 2024-09-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0004_alter_candidatepage_data_alter_candidatepage_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatepage",
            name="data",
        ),
    ]
