# Generated by Django 4.2 on 2024-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0004_remove_candidate_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="municipio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
