# Generated by Django 4.2 on 2024-09-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0005_candidate_municipio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="candidate_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="candidate_nick",
            new_name="nick",
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="election_number",
            new_name="number",
        ),
    ]
