# Generated by Django 4.2 on 2024-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidate",
            "0007_candidate_election_candidate_region_candidate_state_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="state",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="region",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Região"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="uf",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="UF"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="year",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Ano da Eleição"
            ),
        ),
    ]
