# Generated by Django 4.2 on 2024-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0008_remove_candidate_state_alter_candidate_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="election",
        ),
    ]
