# Generated by Django 4.2 on 2024-09-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_tournaments",
                to="tournament.tournament",
            ),
        ),
        migrations.DeleteModel(
            name="TournamentPage",
        ),
    ]
