# Generated by Django 4.2 on 2024-09-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tournament",
            options={"verbose_name": "Torneio", "verbose_name_plural": "Torneios"},
        ),
    ]
