# Generated by Django 4.2 on 2024-09-24 05:45

from django.db import migrations
from home.models import LandingPage
from wagtail.models import Page, Site

def create_homepage(apps, schema_editor):
    new_home = None
    try:
        actual_home = Page.objects.get(slug="home")
        actual_home.slug = 'old-home'
        actual_home.save()

        new_home = LandingPage(slug="home", title="Home", depth=2, path="00010010", url_path="/home/")
        new_home.save()

        page_home_instance = Page.objects.get(slug=new_home.slug)
        actual_site = Site.objects.all().first()
        actual_site.root_page = page_home_instance
        actual_site.save()
    except Exception as e:
        Page.objects.filter(slug="home").delete()
        raise e

def delete_homepage(apps, schema_editor):
    actual_home = Page.objects.get(slug="home")
    previous_home = Page.objects.filter(id__lt=actual_home.id).last()
    actual_site = Site.objects.all().first()
    actual_site.root_page = previous_home
    actual_site.save()
    actual_home.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_alter_competition_tournament_delete_tournamentpage"),
    ]

    operations = [
        migrations.RunPython(create_homepage, delete_homepage),
    ]
