# Generated by Django 4.2 on 2024-09-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="search_image",
        ),
    ]
