# Generated by Django 4.2 on 2024-09-24 05:45

from django.db import migrations

def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User

    User.objects.create_superuser(
        username="admin",
        email="jotadevsolutions@mail.com",
        password="admin",
    )

def remove_first_superuser(apps, schema_editor):
    from django.contrib.auth.models import User

    User.objects.filter(username="admin").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_landingpage_search_image"),
    ]

    operations = [
        migrations.RunPython(create_superuser, remove_first_superuser),
    ]
