# Generated by Django 4.2 on 2024-09-27 15:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_landingpage_subheading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="heading",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="subheading",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Subtítulo"
            ),
        ),
    ]
