# Generated by Django 4.2 on 2024-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_landingpage_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="heading",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Título"
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="subheading",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Subtítulo"
            ),
        ),
    ]
